title: è¯ä¸¸ï¼ğŸ’Š
url: https://pill.fiveyellowmice.com
baseurl: ""
description: è¿™ç ´ç©æ„åƒæ£è¯ä¸¸ï¼

exclude: [Gemfile, Gemfile.lock]

sass:
  style: compressed

collections: 
  pills:
    output: true
    permalink: /:name/

defaults:
  - scope:
      path: ""
      type: pills
    values:
      layout: pill
